# Generated by Django 4.2.1 on 2023-05-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="title",
            field=models.CharField(
                choices=[("Herr", "Herr"), ("Frau", "Frau"), ("Firma", "Firma")],
                default="Herr",
                max_length=5,
            ),
        ),
    ]
