# Generated by Django 4.2.1 on 2023-05-19 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_person_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birthday",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="surname",
            field=models.CharField(default="", max_length=255),
        ),
    ]
