# Generated by Django 4.2.1 on 2023-05-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_person_birthday_person_name_person_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="title",
            field=models.CharField(
                choices=[("Herr", "Herr"), ("Frau", "Frau"), ("Firma", "Firma")],
                max_length=5,
            ),
        ),
    ]
