# Generated by Django 4.2.1 on 2023-05-19 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_alter_person_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name",
            new_name="name_or_company",
        ),
    ]
