# Generated by Django 4.2.1 on 2023-05-19 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_rename_name_person_name_or_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="birthday",
            new_name="date_of_birth",
        ),
    ]
