# Generated by Django 4.2.1 on 2023-07-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0006_rename_birthday_person_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(default="", max_length=255)),
                ("postal_code", models.CharField(default="", max_length=31)),
                ("city", models.CharField(default="", max_length=255)),
                ("country", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
