# Generated by Django 4.2.1 on 2023-07-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="adress",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.adress",
            ),
        ),
    ]
