# Generated by Django 4.2.1 on 2023-07-21 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0011_alter_person_adress_alter_person_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="adress",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.create,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.adress",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(default=None, null=True),
        ),
    ]
